name: Auto Cleanup Old Images
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Delete old files
        run: |
          find images/ -type f -mmin +120 -delete || true
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto clean old images"
